#!/bin/sh
if [ -e /tmp/.nfr4x.inf ]; then
          rm /tmp/.nfr4x.inf
	  break;
else
	LIBDIR=/lib/modules/`uname -r`
	if [ ! -d $LIBDIR ]; then
		LIBDIR=/lib/modules/`ls /lib/modules | tail -n 1`
	fi
	if [ `mount | grep /proc | wc -l` -lt 1 ]; then
		/bin/mount -t proc proc /proc > /dev/null 2>&1
		/bin/mount -t sysfs sysfs /sys > /dev/null 2>&1
		/sbin/depmod -Ae > /dev/null 2>&1
	fi

	echo "MeoBoot is starting mdev"
	echo "/sbin/mdev" > /proc/sys/kernel/hotplug
	/etc/init.d/mdev > /dev/null 2>&1

	sleep 5
	mnttest="nouuid"
	if [ -e /usr/lib/enigma2/python/Plugins/Extensions/MeoBoot/instal  ]; then
        	orgimag1=`mount | sed '/sd/!d' | cut -d" " -f1`
		selectinstall=`cat /usr/lib/enigma2/python/Plugins/Extensions/MeoBoot/instal`
		for item in $orgimag1; do
			selectmnt=`blkid | sed "/$selectinstall/!d" | cut -d":" -f1`
			if [ $selectmnt == $item ]; then
				echo "selectmnt=" $selectmnt
                        	mnttest="uuid"
				mount $selectmnt /media/meoboot > /dev/null 2>&1
			fi
			if [ ! -e /media/meoboot/MbootM  ]; then
				echo "MeoBoot hasn't been installed on: " $selectmnt
				umount /media/meoboot > /dev/null 2>&1 
			else
				echo "MeoBoot has been installed on: " $selectmnt
				break;
			fi 			
		done
	fi	

	if [ ! -e /media/meoboot  ]; then
		mkdir /media/meoboot > /dev/null 2>&1
	fi
	if [ $mnttest == "nouuid" ] ; then
	        echo "MeoBoot mount by Device"
		DEVICES1=`find /dev/sd??`
		for DEVICE in $DEVICES1;
		do
			if [ -e /media/meoboot  ]; then
				echo "meoboot checking installation on: " $DEVICE
				mount $DEVICE /media/meoboot > /dev/null 2>&1 
			fi
			if [ ! -e /media/meoboot/MbootM  ]; then
				echo "MeoBoot hasn't been installed on: " $DEVICE
				umount /media/meoboot > /dev/null 2>&1 
			else
				echo "MeoBoot has been installed on: " $DEVICE
				break;
			fi 
		done
	elif [ $mnttest == "uuid" ]; then	
		echo "MeoBoot mount by UUID"
	fi

	MODPROBE=/sbin/modprobe

	echo "MeoBoot is loading modules"
	for mod in dvb; do
		$MODPROBE $mod
	done

	# Hack for loading modules which are not loaded on diffrent kernel images
	/etc/init.d/modutils.sh
	#

	cat /etc/videomode2 > /proc/stb/video/videomode

	#we must wait until udev has created the video device
	(
	if [ -d /proc/stb ]; then
		while true; do
			if [ -e /dev/dvb/adapter0/video0 ]; then
				break;
			fi;
		done;
	fi;
	[ -e /etc/dropbear/dropbear_rsa_host_key ] && /usr/bin/showiframe /usr/share/bootlogo.mvi || /usr/bin/showiframe /usr/share/bootlogo_wait.mvi;
	) &
        
        sleep 10
        echo "Driverload end"

	if [ -f $LIBDIR/kernel/fs/autofs4/autofs4.ko ]; then
		/sbin/insmod $LIBDIR/kernel/fs/autofs4/autofs4.ko > /dev/null 2>&1
	fi

	if [ -e /tmp/.nfr4x.inf ]; then
		  break;
	fi

	TARGET=Flash
	if [ -f /media/meoboot/MbootM/.meoboot ]; then
	  TARGET=`cat /media/meoboot/MbootM/.meoboot`
	fi
        #TARGET=Flash
	if [ $TARGET = "Flash" ]; then
		echo "MeoBoot is booting image from " $TARGET
		/bin/umount /media/meoboot > /dev/null 2>&1
		/bin/umount /media/usb > /dev/null 2>&1
		/bin/umount /media/hdd > /dev/null 2>&1
		/usr/bin/showiframe /usr/share/bootlogo.mvi > /dev/null 2>&1
	else
		echo "MeoBoot is booting" $TARGET " from " $DEVICE
		if [ -d /media/meoboot/MbootM/$TARGET ]; then
			if [ -f /media/meoboot/MbootM/$TARGET/etc/init.d/udev ]; then
				sed -ie s!"\$4"!"\$3"!g /media/meoboot/MbootM/$TARGET/etc/init.d/udev
			fi
			if [ -f /media/meoboot/MbootM/$TARGET/usr/share/bootlogo.mvi ]; then
				/usr/bin/showiframe /media/meoboot/MbootM/$TARGET/usr/share/bootlogo.mvi
			else
				/usr/bin/showiframe /media/meoboot/MbootM/$TARGET/usr/share/bootlogo.mvi
			fi

			sleep 1

			/bin/mount -o bind /dev /media/meoboot/MbootM/$TARGET/dev
			/bin/mount -o bind /proc /media/meoboot/MbootM/$TARGET/proc
			/bin/mount -o bind /sys /media/meoboot/MbootM/$TARGET/sys
			rm /media/meoboot/MbootM/$TARGET/media/meoboot > /dev/null 2>&1
			mkdir /media/meoboot/MbootM/$TARGET/media/meoboot > /dev/null 2>&1
                        orgimag=`mount | sed '/sd/!d' | cut -d" " -f1`
                        rm -f media/meoboot/MbootM/$TARGET/usr/bin/enigma2_pre_start.sh
                           for item in $orgimag; do
                               ohdd=`echo  $item | cut -d"/" -f3`
                               nhdd=`mount | sed "/\$ohdd/!d" | sed q | cut -d" " -f3`
                               if [ $nhdd == '/media/meoboot' ]; then
                                  echo $nhdd
                                  echo "mkdir "$nhdd  >> media/meoboot/MbootM/$TARGET/usr/bin/enigma2_pre_start.sh
                                  echo "mount "$item $nhdd  >> media/meoboot/MbootM/$TARGET/usr/bin/enigma2_pre_start.sh 
                               else
                                  echo "umount "$nhdd  >> media/meoboot/MbootM/$TARGET/usr/bin/enigma2_pre_start.sh
                                  echo "mkdir "$nhdd  >> media/meoboot/MbootM/$TARGET/usr/bin/enigma2_pre_start.sh
                                  echo "mount "$item $nhdd  >> media/meoboot/MbootM/$TARGET/usr/bin/enigma2_pre_start.sh 
                                  echo ok 
                               fi    
                           done	
                        chmod 755 media/meoboot/MbootM/$TARGET/usr/bin/enigma2_pre_start.sh   
			#/bin/mount /dev/sda1 /media/meoboot/MbootM/$TARGET/media/hdd
			if [ -f /media/meoboot/MbootM/$TARGET/sbin/init.sysvinit ]; then
				exec /usr/sbin/chroot /media/meoboot/MbootM/$TARGET /sbin/init.sysvinit
			fi
			exit 0
		fi
	fi
fi
# boot Flash 

if [ -f /sbin/init.sysvinit ]; then
		#echo "Running /sbin/init.sysvinit"
		exec /sbin/init.sysvinit $1
fi

exit 0
